services:
  - type: web
    name: python-keyword-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: app.py